spring:
  mvc:
    view:
      suffix: .html
  profiles:
    active: dev
    include: oauth2
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: rlagusdn
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 399313694963-ssl5np4ejbnctin79f5ti4rgp2agf5i9.apps.googleusercontent.com
            client-secret: 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
            scope :
              - profile
              - email
  output:
    ansi:
      enabled: always
logging:
  file:
    path:
  config:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    #org.springframework.jdbc.core.StatementCreatorUtils: TRACE


# cors 설정
cors:
  allowed-origins: 'http://localhost:3000'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

# jwt secret key 설정
jwt:
  secret: '8sknjlO3NPTBqo319DHLNqsQAfRJEdKsETOds'

# 토큰 관련 secret Key 및 RedirectUri 설정
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth/redirect